const fs = require('fs');
let code = fs.readFileSync('src/components/VpnKeysManager.tsx', 'utf8');

code = code.replace(/activeVpnKeysTitle: lang === 'fa' \? 'کانفیگ‌ها و اشتراک‌های فعال VPN' : 'Active VPN Subscription Keys',/g, 
  "activeVpnKeysTitle: translateText('Active VPN Subscription Keys', 'کانفیگ‌ها و اشتراک‌های فعال VPN', lang),");

code = code.replace(/activeVpnKeysDesc: lang === 'fa' \? 'این کانفیگ‌ها مستقیماً لینک‌های تولید شده توسط ربات هستند که در دیتابیس ۳x-ui یا sqlite ذخیره شده‌اند\.' : 'These represent the subscription links generated by the Python bot and saved in sqlite\/3x-ui\.',/g, 
  "activeVpnKeysDesc: translateText('These represent the subscription links generated by the Python bot and saved in sqlite/3x-ui.', 'این کانفیگ‌ها مستقیماً لینک‌های تولید شده توسط ربات هستند که در دیتابیس ۳x-ui یا sqlite ذخیره شده‌اند.', lang),");

code = code.replace(/keySubLinkLabel: lang === 'fa' \? 'لینک اتصال اختصاصی' : 'Subscription Link',/g, 
  "keySubLinkLabel: translateText('Subscription Link', 'لینک اتصال اختصاصی', lang),");

code = code.replace(/keyOwnerLabel: lang === 'fa' \? 'صاحب کانفیگ \(کاربر\)' : 'Owner ID\/Handle',/g, 
  "keyOwnerLabel: translateText('Owner ID/Handle', 'صاحب کانفیگ (کاربر)', lang),");

code = code.replace(/keyExpiryLabel: lang === 'fa' \? 'تاریخ انقضا اکانت' : 'Expiry Date'/g, 
  "keyExpiryLabel: translateText('Expiry Date', 'تاریخ انقضا اکانت', lang)");

fs.writeFileSync('src/components/VpnKeysManager.tsx', code);
