import { translateText, Language } from "../lang/locales";
import React, { useState } from 'react';
import { formatDateTime } from "../utils/dateTimeUtils";
import {
  Search,
  Key,
  Copy,
  Check,
  Ban,
  Trash2,
  RefreshCw,
  RotateCcw,
  QrCode,
  X,
  CreditCard,
  Filter,
  ArrowUpDown,
  ChevronDown
} from 'lucide-react';


// Assuming types from other files...
export function VpnKeysManager({
  keys,
  users,
  lang,
  toggleSubscriptionKey,
  deleteSubscriptionKey,
  deleteExpiredSubscriptionKeys,
  setDeleteConfirm,
  updateSubscriptionKey,
  servers = [],
  settings,
}: any) {
  const [searchTerm, setSearchTerm] = useState("");
  const [copiedKeyId, setCopiedKeyId] = useState<string | null>(null);
  const [activeQrKey, setActiveQrKey] = useState<any | null>(null);
  const [regeneratingKeyId, setRegeneratingKeyId] = useState<string | null>(null);
  const [renewingKey, setRenewingKey] = useState<any | null>(null);
  const [renewGb, setRenewGb] = useState("30");
  const [renewDays, setRenewDays] = useState("30");
  const [isRenewing, setIsRenewing] = useState(false);
  const [isDeletingExpired, setIsDeletingExpired] = useState(false);
  const [statusFilter, setStatusFilter] = useState<string>("all");
  const [sortOption, setSortOption] = useState<string>("newest");

  const t = {
    activeVpnKeysTitle: translateText('Active VPN Subscription Keys', 'کانفیگ‌ها و اشتراک‌های فعال VPN', lang),
    activeVpnKeysDesc: translateText('These represent the subscription links generated by the Python bot and saved in sqlite/3x-ui.', 'این کانفیگ‌ها مستقیماً لینک‌های تولید شده توسط ربات هستند که در دیتابیس Xray یا sqlite ذخیره شده‌اند.', lang),
    keySubLinkLabel: translateText('Subscription Link', 'لینک اتصال اختصاصی', lang),
    keyOwnerLabel: translateText('Owner ID/Handle', 'صاحب کانفیگ (کاربر)', lang),
    keyExpiryLabel: translateText('Expiry Date', 'تاریخ انقضا اکانت', lang)
  };

  const copyTextToClipboard = async (text: string) => {
    try {
      await navigator.clipboard.writeText(text);
    } catch (err) {
      console.error("Failed to copy:", err);
    }
  };

  const handleRegenerateUuid = async (keyId: string) => {
    const confirmMsg = translateText("Are you sure you want to regenerate UUID and link? This will drop current connections.", "آیا از تغییر لینک و UUID این کانفیگ مطمئن هستید؟ این کار باعث قطع اتصال فعلی کاربر می‌شود.", lang);
    
    const doRegen = async () => {
      setRegeneratingKeyId(keyId);
      try {
        const response = await fetch(`/api/subscription-keys/${keyId}/regenerate`, {
          method: "POST"
        });
        if (response.ok) {
          const result = await response.json();
          updateSubscriptionKey(keyId, {
            clientUuid: result.newUuid,
            subLink: result.newSubLink
          });
        }
      } catch (err) {
        console.error(err);
      } finally {
        setRegeneratingKeyId(null);
      }
    };

    if (setDeleteConfirm) {
      setDeleteConfirm({
        id: `regen_${keyId}`,
        type: "regen_key",
        title: translateText("Regenerate Link", "تغییر لینک و UUID", lang),
        message: confirmMsg,
        onConfirm: doRegen
      });
    } else if (window.confirm(confirmMsg)) {
      doRegen();
    }
  };

  const handleRenewSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!renewingKey) return;
    setIsRenewing(true);
    try {
      const response = await fetch(`/api/subscription-keys/${renewingKey.id}/renew`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          addTrafficGb: parseFloat(renewGb) || 0,
          addDays: parseInt(renewDays) || 0
        })
      });

      if (response.ok) {
        const result = await response.json();
        updateSubscriptionKey(renewingKey.id, {
          trafficLimitGb: result.newTrafficLimitGb,
          expireDate: result.newExpireDate,
          status: 'active'
        });
        alert(translateText("Subscription renewed successfully!", "اشتراک با موفقیت تمدید شد!", lang));
        setRenewingKey(null);
      } else {
        const err = await response.json();
        alert("Error: " + err.error);
      }
    } catch (err) {
      console.error(err);
      alert("Network error");
    } finally {
      setIsRenewing(false);
    }
  };

  const handleDeleteExpired = async () => {
    if (statusCounts.expired === 0) {
      if (setDeleteConfirm) {
        setDeleteConfirm({
          id: "no_expired",
          type: "info",
          title: translateText("No Expired Configs", "عدم وجود کانفیگ منقضی", lang),
          message: translateText("No expired configs found to delete.", "هیچ کانفیگ منقضی‌شده‌ای برای حذف یافت نشد.", lang)
        });
      } else {
        alert(translateText("No expired configs found to delete.", "هیچ کانفیگ منقضی‌شده‌ای برای حذف یافت نشد.", lang));
      }
      return;
    }

    const confirmMsg = translateText(
      `Are you sure you want to delete all ${statusCounts.expired} expired config(s)?`,
      `آیا از حذف تمامی ${statusCounts.expired} کانفیگ منقضی شده اطمینان دارید؟\n\nتعداد کانفیگ منقضی: ${statusCounts.expired}\n\nاین کانفیگ‌ها همزمان از:\n• تمامی سرورهای VPN (۳x-ui / مرزبان / پاسارگاد / ربکا / D-UI)\n• داشبورد مدیریت\n• ربات تلگرام\n• بخش «اشتراک‌های من» مشتریان\nبه‌طور کامل و دائم پاک خواهند شد.`,
      lang
    );

    if (setDeleteConfirm) {
      setDeleteConfirm({
        id: "all_expired",
        type: "expired_keys",
        title: translateText("Confirm Bulk Delete Expired Configs", "تایید حذف همه‌جانبه کانفیگ‌های منقضی شده", lang),
        message: confirmMsg
      });
    } else {
      if (!window.confirm(confirmMsg)) return;
      setIsDeletingExpired(true);
      try {
        if (deleteExpiredSubscriptionKeys) {
          await deleteExpiredSubscriptionKeys();
        } else {
          const res = await fetch("/api/subscription-keys/delete-expired", {
            method: "POST",
            headers: { "Content-Type": "application/json" }
          });
          const data = await res.json();
          if (data.success) {
            if (typeof window !== "undefined") window.location.reload();
          }
        }
      } catch (err: any) {
        console.error(err);
      } finally {
        setIsDeletingExpired(false);
      }
    }
  };

  const getKeyStatus = (key: any) => {
    const isExplicitDisabled = key.status === "disabled";
    const nowSec = Date.now() / 1000;
    const nowMs = Date.now();
    const limitGb = Number(key.trafficLimitGb || key.totalGb || 0);
    const usedGb = Number(key.trafficUsedGb || key.usedGb || 0);
    
    const isDateExpired = key.expireDate && !isNaN(new Date(key.expireDate).getTime()) && new Date(key.expireDate).getTime() < nowMs;
    const isTsExpired = key.expireTimestamp && Number(key.expireTimestamp) > 0 && Number(key.expireTimestamp) < nowSec;
    const isVolumeExpired = limitGb > 0 && usedGb >= limitGb;

    const isExpired = key.status === "expired" || isTsExpired || isDateExpired || isVolumeExpired;
    if (isExpired) return "expired";
    if (isExplicitDisabled) return "disabled";
    
    // Remaining traffic in GB
    const remGb = limitGb > 0 ? limitGb - usedGb : Infinity;

    // Remaining time in days
    let remDays = Infinity;
    if (key.expireTimestamp && Number(key.expireTimestamp) > 0) {
      const expSec = Number(key.expireTimestamp);
      if (expSec > nowSec) {
        remDays = Math.min(remDays, (expSec - nowSec) / 86400);
      } else {
        remDays = 0;
      }
    }
    if (key.expireDate) {
      const expMs = new Date(key.expireDate).getTime();
      if (!isNaN(expMs) && expMs > 0) {
        if (expMs > nowMs) {
          remDays = Math.min(remDays, (expMs - nowMs) / (1000 * 60 * 60 * 24));
        } else {
          remDays = 0;
        }
      }
    }

    // Depleting: remaining volume <= 1.0 GB OR remaining time <= 1.0 day
    const isVolumeDepleting = limitGb > 0 && remGb > 0 && remGb <= 1.0;
    const isTimeDepleting = remDays > 0 && remDays <= 1.0;

    const isDepleting = isVolumeDepleting || isTimeDepleting;

    if (isDepleting) return "depleting";
    return "active";
  };

  const keysArray = Array.isArray(keys) ? keys : [];
  
  const statusCounts = {
    all: keysArray.length,
    active: keysArray.filter(k => {
      const s = getKeyStatus(k);
      return s === "active" || s === "depleting";
    }).length,
    depleting: keysArray.filter(k => getKeyStatus(k) === "depleting").length,
    disabled: keysArray.filter(k => getKeyStatus(k) === "disabled").length,
    expired: keysArray.filter(k => getKeyStatus(k) === "expired").length,
  };

  const sortOptions = [
    { id: "newest", label: translateText("Newest first", "جدیدترین", lang) },
    { id: "oldest", label: translateText("Oldest first", "قدیمی‌ترین", lang) },
    { id: "recently_updated", label: translateText("Recently active / updated", "آخرین فعالیت / بروزرسانی", lang) },
    { id: "name_asc", label: translateText("Name / Email A → Z", "نام الف تا ی", lang) },
    { id: "name_desc", label: translateText("Name / Email Z → A", "نام ی تا الف", lang) },
    { id: "most_traffic", label: translateText("Most traffic used", "بیشترین مصرف ترافیک", lang) },
    { id: "highest_remaining", label: translateText("Highest remaining traffic", "بیشترین حجم باقی‌مانده", lang) },
    { id: "expiry_asc", label: translateText("Nearest expiry date", "نزدیک‌ترین تاریخ انقضا", lang) },
  ];

  const filteredAndSortedKeys = keysArray
    .filter((key: any) => {
      const status = getKeyStatus(key);
      if (statusFilter !== "all") {
        if (statusFilter === "active") {
          if (status !== "active" && status !== "depleting") return false;
        } else if (status !== statusFilter) {
          return false;
        }
      }

      if (!searchTerm) return true;
      const term = searchTerm.toLowerCase();
      const user = users?.find((u: any) => u.userId === key.userId);
      return (
        (key.id || "").toLowerCase().includes(term) ||
        (key.clientName || "").toLowerCase().includes(term) ||
        (key.email || "").toLowerCase().includes(term) ||
        (key.remark || "").toLowerCase().includes(term) ||
        (key.planName || "").toLowerCase().includes(term) ||
        String(key.userId).includes(term) ||
        (user?.username || "").toLowerCase().includes(term)
      );
    })
    .sort((a: any, b: any) => {
      const getTimestamp = (k: any) => {
        if (k.createdAtMs) return Number(k.createdAtMs);
        if (k.createdAt) {
          const d = new Date(k.createdAt);
          if (!isNaN(d.getTime())) return d.getTime();
        }
        if (k.id && k.id.startsWith("SUB-")) {
          const parts = k.id.split("-");
          if (parts.length >= 2) {
            const ts = Number(parts[1]);
            if (!isNaN(ts) && ts > 100000000) return ts;
          }
        }
        return 0;
      };

      const getName = (k: any) => (k.clientName || k.email || k.remark || k.id || "").toLowerCase();
      const getUsed = (k: any) => Number(k.usedGb || 0);
      const getRemaining = (k: any) => {
        const tot = Number(k.trafficLimitGb || k.totalGb || 0);
        return tot > 0 ? Math.max(0, tot - Number(k.usedGb || 0)) : 999999;
      };
      const getExpiry = (k: any) => Number(k.expireTimestamp || 9999999999);

      switch (sortOption) {
        case "oldest":
          return getTimestamp(a) - getTimestamp(b);
        case "newest":
          return getTimestamp(b) - getTimestamp(a);
        case "recently_updated":
          return (Number(b.lastSyncMs || 0) || getTimestamp(b)) - (Number(a.lastSyncMs || 0) || getTimestamp(a));
        case "name_asc":
          return getName(a).localeCompare(getName(b));
        case "name_desc":
          return getName(b).localeCompare(getName(a));
        case "most_traffic":
          return getUsed(b) - getUsed(a);
        case "highest_remaining":
          return getRemaining(b) - getRemaining(a);
        case "expiry_asc":
          return getExpiry(a) - getExpiry(b);
        default:
          return getTimestamp(b) - getTimestamp(a);
      }
    });

  return (
    <div className="space-y-6 max-w-4xl mx-auto">
      {/* Title */}
      <div>
        <h2 className="text-xl md:text-2xl font-display font-bold text-white flex items-center gap-3">
          <Key className="w-6 h-6 text-indigo-400" />
          {t.activeVpnKeysTitle}
        </h2>
        <p className="text-gray-400 text-sm mt-1">
          {t.activeVpnKeysDesc}
        </p>
      </div>

      {/* Top Status Counters & Filter Pills */}
      <div className="grid grid-cols-2 sm:grid-cols-5 gap-2.5">
        <button
          onClick={() => setStatusFilter("all")}
          className={`p-3 rounded-xl border transition-all text-right flex flex-col justify-between ${
            statusFilter === "all"
              ? "bg-indigo-600/20 border-indigo-500 text-white shadow-[0_0_12px_rgba(99,102,241,0.25)]"
              : "bg-[#111827] border-[#1f2937] text-gray-400 hover:border-gray-700 hover:text-gray-200"
          }`}
        >
          <span className="text-xs font-medium text-gray-400">{translateText("All Configs", "همه کانفیگ‌ها", lang)}</span>
          <div className="flex items-center justify-between mt-1">
            <span className="w-2 h-2 rounded-full bg-indigo-400"></span>
            <span className="text-lg font-bold font-mono text-white">{statusCounts.all}</span>
          </div>
        </button>

        <button
          onClick={() => setStatusFilter("active")}
          className={`p-3 rounded-xl border transition-all text-right flex flex-col justify-between ${
            statusFilter === "active"
              ? "bg-emerald-600/20 border-emerald-500 text-white shadow-[0_0_12px_rgba(16,185,129,0.25)]"
              : "bg-[#111827] border-[#1f2937] text-gray-400 hover:border-gray-700 hover:text-gray-200"
          }`}
        >
          <span className="text-xs font-medium text-emerald-400/90">{translateText("Active", "فعال", lang)}</span>
          <div className="flex items-center justify-between mt-1">
            <span className="w-2.5 h-2.5 rounded-full bg-emerald-500 animate-pulse"></span>
            <span className="text-lg font-bold font-mono text-emerald-400">{statusCounts.active}</span>
          </div>
        </button>

        <button
          onClick={() => setStatusFilter("depleting")}
          className={`p-3 rounded-xl border transition-all text-right flex flex-col justify-between ${
            statusFilter === "depleting"
              ? "bg-amber-600/20 border-amber-500 text-white shadow-[0_0_12px_rgba(245,158,11,0.25)]"
              : "bg-[#111827] border-[#1f2937] text-gray-400 hover:border-gray-700 hover:text-gray-200"
          }`}
        >
          <span className="text-xs font-medium text-amber-400/90">{translateText("Depleting", "رو به اتمام", lang)}</span>
          <div className="flex items-center justify-between mt-1">
            <span className="w-2.5 h-2.5 rounded-full bg-amber-500"></span>
            <span className="text-lg font-bold font-mono text-amber-400">{statusCounts.depleting}</span>
          </div>
        </button>

        <button
          onClick={() => setStatusFilter("disabled")}
          className={`p-3 rounded-xl border transition-all text-right flex flex-col justify-between ${
            statusFilter === "disabled"
              ? "bg-slate-600/20 border-slate-500 text-white shadow-[0_0_12px_rgba(148,163,184,0.25)]"
              : "bg-[#111827] border-[#1f2937] text-gray-400 hover:border-gray-700 hover:text-gray-200"
          }`}
        >
          <span className="text-xs font-medium text-slate-400">{translateText("Disabled", "غیرفعال", lang)}</span>
          <div className="flex items-center justify-between mt-1">
            <span className="w-2.5 h-2.5 rounded-full bg-slate-500"></span>
            <span className="text-lg font-bold font-mono text-slate-300">{statusCounts.disabled}</span>
          </div>
        </button>

        <button
          onClick={() => setStatusFilter("expired")}
          className={`p-3 rounded-xl border transition-all text-right flex flex-col justify-between ${
            statusFilter === "expired"
              ? "bg-rose-600/20 border-rose-500 text-white shadow-[0_0_12px_rgba(244,63,94,0.25)]"
              : "bg-[#111827] border-[#1f2937] text-gray-400 hover:border-gray-700 hover:text-gray-200"
          }`}
        >
          <span className="text-xs font-medium text-rose-400/90">{translateText("Expired", "منقضی شده", lang)}</span>
          <div className="flex items-center justify-between mt-1">
            <span className="w-2.5 h-2.5 rounded-full bg-rose-500"></span>
            <span className="text-lg font-bold font-mono text-rose-400">{statusCounts.expired}</span>
          </div>
        </button>
      </div>

      {/* Search and Sort Toolbar */}
      <div className="flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-3 bg-[#111827] p-3 rounded-2xl border border-[#1f2937]">
        {/* Search input */}
        <div className="relative flex-1">
          <input
            type="text"
            placeholder={translateText("Search email, comment, sub ID, UUID...", "جستجو براساس نام، ایمیل، شناسه یا UUID...", lang)}
            className="w-full bg-[#1f2937]/70 border border-[#374151] rounded-xl pl-10 pr-4 py-2 text-sm text-white focus:outline-none focus:border-indigo-500 placeholder:text-gray-500 transition"
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
          />
          <Search className="w-4 h-4 text-gray-400 absolute left-3 top-3" />
          {searchTerm && (
            <button
              onClick={() => setSearchTerm("")}
              className="absolute right-3 top-2.5 text-gray-400 hover:text-white p-0.5"
            >
              <X className="w-4 h-4" />
            </button>
          )}
        </div>

        {/* Sort Controls & Bulk Actions */}
        <div className="flex items-center gap-2 flex-wrap sm:flex-nowrap">
          <div className="relative flex-1 sm:flex-initial flex items-center">
            <ArrowUpDown className="w-3.5 h-3.5 text-indigo-400 absolute left-3 pointer-events-none z-10" />
            <select
              value={sortOption}
              onChange={(e) => setSortOption(e.target.value)}
              className="w-full sm:w-auto appearance-none bg-[#1f2937] hover:bg-slate-800 border border-[#374151] pl-8 pr-8 py-2 rounded-xl text-xs font-medium text-slate-200 focus:outline-none focus:border-indigo-500 cursor-pointer transition shadow-sm"
            >
              {sortOptions.map((opt) => (
                <option key={opt.id} value={opt.id} className="bg-[#1f2937] text-gray-200 py-1.5">
                  {opt.label}
                </option>
              ))}
            </select>
            <ChevronDown className="w-3.5 h-3.5 text-gray-400 absolute right-2.5 pointer-events-none z-10" />
          </div>

          <button
            onClick={handleDeleteExpired}
            disabled={isDeletingExpired || statusCounts.expired === 0}
            className="flex items-center justify-center gap-2 px-3.5 py-2 bg-gradient-to-r from-rose-600 to-red-600 hover:from-rose-500 hover:to-red-500 disabled:opacity-40 disabled:cursor-not-allowed text-white text-xs font-bold rounded-xl transition-all shadow-md cursor-pointer whitespace-nowrap"
            title={translateText("Delete all expired configs from panel, bot & dashboard", "حذف همه‌جانبه تمامی کانفیگ‌های منقضی شده از سرور، ربات و پنل", lang)}
          >
            {isDeletingExpired ? (
              <RefreshCw className="w-3.5 h-3.5 animate-spin" />
            ) : (
              <Trash2 className="w-3.5 h-3.5" />
            )}
            <span>
              {translateText("Delete Expired Configs", "حذف کانفیگ‌های منقضی شده", lang)}
              {statusCounts.expired > 0 && (
                <span className="mr-1 px-1.5 py-0.5 bg-black/40 text-rose-200 text-[10px] rounded font-mono">
                  {statusCounts.expired}
                </span>
              )}
            </span>
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-2 gap-4">
        {filteredAndSortedKeys.length > 0 ? filteredAndSortedKeys.map((key: any) => {
          const user = users?.find((u: any) => u.userId === key.userId);
          const cardStatus = getKeyStatus(key);
          const badgeStyle =
            cardStatus === "active"
              ? "bg-emerald-500/10 text-emerald-400 border-emerald-500/20"
              : cardStatus === "depleting"
              ? "bg-amber-500/10 text-amber-400 border-amber-500/20"
              : cardStatus === "disabled"
              ? "bg-slate-500/10 text-slate-400 border-slate-500/20"
              : "bg-rose-500/10 text-rose-400 border-rose-500/20";
          const badgeLabel =
            cardStatus === "active"
              ? translateText("active", "فعال", lang)
              : cardStatus === "depleting"
              ? translateText("depleting", "رو به اتمام", lang)
              : cardStatus === "disabled"
              ? translateText("disabled", "غیرفعال", lang)
              : translateText("expired", "منقضی شده", lang);

          return (
            <div key={key.id} className="bg-[#111827]/40 border border-slate-800/40 rounded-lg p-5 space-y-4 relative overflow-hidden group flex flex-col hover:border-cyan-500/50 transition-colors backdrop-blur-md">
              <div className="absolute top-0 right-0 h-1.5 w-full bg-cyan-500 shadow-[0_0_10px_rgba(34,211,238,0.5)]"></div>
              
              <div className="flex flex-col sm:flex-row justify-between items-start gap-4">
                <div>
                  <h4 className="font-semibold text-white text-base flex items-center gap-2">
                    {key.planName}
                  </h4>
                  <span className="text-xs text-gray-400 font-mono block mt-1">Key ID: {key.id}</span>
                  <span className="text-xs text-indigo-400 font-mono block mt-0.5" title="Client/Config Name">
                    Client Name: {key.clientName || 'N/A'}
                  </span>
                  <span className="text-xs text-gray-500 font-mono block mt-0.5" title="Telegram User ID">
                    Telegram ID: {key.userId}
                  </span>
                  <span className="text-xs text-gray-500 font-mono block mt-0.5 truncate" title="UUID">
                    UUID: {key.clientUuid || 'N/A'}
                  </span>
                </div>
                <div className="flex flex-wrap items-center gap-2">
                  <span className={`px-2.5 py-1 rounded text-xs font-semibold border uppercase ${badgeStyle}`}>
                    {badgeLabel}
                  </span>
                  <button
                    onClick={() => {
                      copyTextToClipboard(key.subLink);
                      setCopiedKeyId(key.id);
                      setTimeout(() => setCopiedKeyId(null), 1500);
                    }}
                    className="px-2.5 py-1 bg-indigo-500/10 hover:bg-indigo-500/20 text-indigo-400 border border-indigo-500/20 hover:border-indigo-500/40 rounded text-xs font-medium flex items-center gap-1.5 transition-all cursor-pointer"
                    title={translateText("Copy subscription link", "کپی لینک کانفیگ", lang)}
                  >
                    {copiedKeyId === key.id ? (
                      <>
                        <Check className="w-3.5 h-3.5 text-emerald-400 animate-bounce" />
                        <span>{translateText("Copied", "کپی شد", lang)}</span>
                      </>
                    ) : (
                      <>
                        <Copy className="w-3.5 h-3.5 text-indigo-400" />
                        <span>{translateText("Copy", "کپی", lang)}</span>
                      </>
                    )}
                  </button>
                  <button
                    onClick={() => setActiveQrKey(key)}
                    className="px-2.5 py-1 bg-violet-500/10 hover:bg-violet-500/20 text-violet-400 border border-violet-500/20 hover:border-violet-500/40 rounded text-xs font-medium flex items-center gap-1.5 transition-all cursor-pointer"
                    title={translateText("Show QR Code", "نمایش بارکد QR", lang)}
                  >
                    <QrCode className="w-3.5 h-3.5 text-violet-400" />
                    <span>{translateText("QR", "بارکد", lang)}</span>
                  </button>
                  <button
                    type="button"
                    onClick={() => handleRegenerateUuid(key.id)}
                    disabled={regeneratingKeyId === key.id}
                    className="px-2.5 py-1 bg-rose-500/10 hover:bg-rose-500/20 text-rose-400 border border-rose-500/20 hover:border-rose-500/40 rounded text-xs font-medium flex items-center gap-1.5 transition-all cursor-pointer disabled:opacity-50"
                    title={translateText("Reset SubLink and UUID", "تغییر لینک و آیدی (UUID/subId)", lang)}
                  >
                    <RotateCcw className={`w-4 h-4 text-rose-400 ${regeneratingKeyId === key.id ? 'animate-spin' : ''}`} />
                    <span>{translateText("New Link", "تغییر لینک", lang)}</span>
                  </button>
                  <button
                    onClick={() => {
                      setRenewingKey(key);
                      setRenewGb("30");
                      setRenewDays("30");
                    }}
                    className="px-2.5 py-1 bg-emerald-500/10 hover:bg-emerald-500/20 text-emerald-400 border border-emerald-500/20 hover:border-emerald-500/40 rounded text-xs font-medium flex items-center gap-1.5 transition-all cursor-pointer"
                    title={translateText("Renew Subscription", "تمدید اشتراک", lang)}
                  >
                    <RefreshCw className="w-3.5 h-3.5 text-emerald-400" />
                    <span>{translateText("Renew", "تمدید", lang)}</span>
                  </button>
                  <button
                    onClick={() => toggleSubscriptionKey(key.id)}
                    className={`px-2.5 py-1 rounded text-xs font-medium flex items-center gap-1.5 transition-all cursor-pointer ${
                      key.status === "active"
                        ? "bg-amber-500/10 text-amber-500 border border-amber-500/20 hover:bg-amber-500/20"
                        : "bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 hover:bg-emerald-500/20"
                    }`}
                    title={key.status === "active" ? (translateText("Disable", "غیرفعال کردن", lang)) : (translateText("Enable", "فعال کردن", lang))}
                  >
                    <Ban className="w-3.5 h-3.5" />
                    <span>{key.status === "active" ? (translateText("Suspend", "تعلیق", lang)) : (translateText("Active", "فعال", lang))}</span>
                  </button>
                  <button
                    onClick={() => setDeleteConfirm({
                      id: key.id,
                      type: "key",
                      title: translateText("Confirm Delete Subscription", "تایید حذف کانفیگ", lang),
                      message: translateText(`Are you sure you want to delete config ${key.planName} (ID: ${key.id})?`, `آیا از حذف دائم کانفیگ ${key.planName} (شناسه: ${key.id}) اطمینان دارید؟`, lang)
                    })}
                    className="p-1.5 text-gray-400 hover:text-rose-400 hover:bg-rose-500/10 rounded transition cursor-pointer"
                    title={translateText("Delete VPN Subscription", "حذف کانفیگ", lang)}
                  >
                    <Trash2 className="w-4 h-4" />
                  </button>
                </div>
              </div>

              <div className="space-y-2 bg-[#1a2234] p-3.5 rounded-lg text-sm border border-slate-800">
                <div className="flex justify-between items-center">
                  <span className="text-gray-400 block text-xs uppercase font-mono tracking-wider font-semibold">{t.keySubLinkLabel}</span>
                  <button
                    onClick={() => {
                      copyTextToClipboard(key.subLink);
                      setCopiedKeyId(key.id);
                      setTimeout(() => setCopiedKeyId(null), 1500);
                    }}
                    className="text-indigo-400 hover:text-indigo-300 p-1 rounded transition cursor-pointer"
                    title={translateText("Copy Link", "کپی لینک", lang)}
                  >
                    {copiedKeyId === key.id ? (
                      <Check className="w-4 h-4 text-emerald-400 animate-pulse" />
                    ) : (
                      <Copy className="w-4 h-4" />
                    )}
                  </button>
                </div>
                <input
                  type="text"
                  readOnly
                  className="bg-black/30 border border-slate-800 rounded p-2 text-xs text-indigo-300 font-mono w-full focus:outline-none select-all"
                  value={key.subLink}
                />
              </div>

              <div className="grid grid-cols-2 gap-4 text-sm pt-4 text-gray-400 border-t border-slate-800">
                <div>
                  <span className="text-xs block text-gray-500 mb-1">{t.keyOwnerLabel}:</span>
                  <span className="text-white font-mono font-medium text-sm">@{user?.username || key.userId}</span>
                </div>
                <div>
                  <span className="text-xs block text-gray-500 mb-1">{t.keyExpiryLabel}:</span>
                  <span className="text-gray-200 font-mono text-sm">
                    {key.expireDate ? formatDateTime(key.expireDate, { timeZone: settings?.timeZone, calendarSystem: settings?.calendarSystem, includeTime: true }) : "-"}
                  </span>
                </div>
                {key.serverId && (
                  <div className="col-span-2">
                    <span className="text-xs block text-gray-500 mb-1">{translateText("Server:", "سرور:", lang)}</span>
                    <span className="text-white font-mono text-sm block bg-black/20 p-2 rounded border border-slate-800">
                      {servers.find((s: any) => String(s.id) === String(key.serverId))?.name || key.serverId}
                    </span>
                  </div>
                )}
                <div className="col-span-2">
                  <span className="text-xs block text-gray-500 mb-1">{translateText("Used / Remaining data:", "حجم مصرفی / باقی‌مانده:", lang)}</span>
                  <span className="text-white font-mono text-sm block bg-black/20 p-2 rounded border border-slate-800">
                    <span className="text-rose-400">{Number(key.trafficUsedGb || 0).toFixed(2)} GB</span>
                    <span className="text-gray-600 mx-2">/</span>
                    <span className="text-emerald-400 font-bold">{Math.max(0, Number(key.trafficLimitGb || 0) - Number(key.trafficUsedGb || 0)).toFixed(2)} GB</span>
                    <span className="text-gray-500 ml-3">({translateText("Total:", "کل:", lang)} {Number(key.trafficLimitGb || 0).toFixed(2)} GB)</span>
                  </span>
                </div>
              </div>
            </div>
          );
        }) : (
          <div className="col-span-full py-12 text-center text-gray-500 bg-slate-900/20 rounded-2xl border border-white/5">
            {translateText("No VPN configs found", "هیچ کانفیگی یافت نشد", lang)}
          </div>
        )}
      </div>

      {/* QR Code Dialog Modal */}
      {activeQrKey && (
        <div className="fixed inset-0 bg-black/80 backdrop-blur-sm flex items-center justify-center p-4 z-50">
          <div className="bg-white p-6 rounded-2xl max-w-sm w-full space-y-6 relative flex flex-col items-center">
            <button
              onClick={() => setActiveQrKey(null)}
              className="absolute top-4 right-4 text-gray-400 hover:text-gray-600 bg-gray-100 hover:bg-gray-200 p-1.5 rounded-full transition-colors cursor-pointer"
            >
              <X className="w-5 h-5" />
            </button>
            <div className="text-center space-y-1">
              <h3 className="font-display font-bold text-gray-900 text-xl">{activeQrKey.planName}</h3>
              <p className="text-gray-500 text-sm font-mono">{activeQrKey.clientName}</p>
            </div>
            
            <div className="p-4 bg-gray-50 rounded-xl border border-gray-100">
              <img
                src={`https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=${encodeURIComponent(activeQrKey.subLink)}`}
                alt="VPN Connection QR Code"
                className="w-full h-auto aspect-square rounded select-none"
                referrerPolicy="no-referrer"
              />
            </div>
            
            <p className="text-center text-gray-500 text-xs">
              {translateText("Scan this QR code with your client app to connect.", "برای اتصال، این بارکد را با اپلیکیشن کلاینت خود اسکن کنید.", lang)}
            </p>
          </div>
        </div>
      )}

      {/* Renew Subscription Modal */}
      {renewingKey && (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-xs flex items-center justify-center p-4 z-50">
          <div className="bg-[#111827] border border-[#1f2937] p-6 rounded-xl max-w-md w-full space-y-5">
            <h3 className="font-display font-semibold text-lg text-white flex items-center gap-2">
              <RefreshCw className="w-5 h-5 text-emerald-400" />
              {translateText("Renew & Recharge Subscription", "تمدید و شارژ اشتراک", lang)}
            </h3>
            
            <div className="bg-[#1a2234] p-3 rounded-lg border border-[#374151] space-y-1">
              <p className="text-sm text-gray-300">
                <span className="text-gray-500 mr-2">{translateText("User:", "کاربر:", lang)}</span>
                <span className="font-mono text-indigo-400">{renewingKey.clientName}</span>
              </p>
              <p className="text-sm text-gray-300">
                <span className="text-gray-500 mr-2">{translateText("Plan:", "پلن:", lang)}</span>
                <span>{renewingKey.planName}</span>
              </p>
            </div>

            <form onSubmit={handleRenewSubmit} className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-1">
                  {translateText("Add Traffic (GB)", "اضافه کردن حجم (گیگابایت)", lang)}
                </label>
                <input
                  type="number"
                  min="0"
                  step="0.1"
                  required
                  className="w-full bg-[#1a2234] border border-[#374151] rounded-lg px-4 py-2.5 text-white focus:outline-none focus:border-emerald-500 focus:ring-1 focus:ring-emerald-500 transition-all font-mono"
                  value={renewGb}
                  onChange={(e) => setRenewGb(e.target.value)}
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-300 mb-1">
                  {translateText("Add Time (Days)", "اضافه کردن زمان (روز)", lang)}
                </label>
                <input
                  type="number"
                  min="0"
                  required
                  className="w-full bg-[#1a2234] border border-[#374151] rounded-lg px-4 py-2.5 text-white focus:outline-none focus:border-emerald-500 focus:ring-1 focus:ring-emerald-500 transition-all font-mono"
                  value={renewDays}
                  onChange={(e) => setRenewDays(e.target.value)}
                />
              </div>

              <div className="flex items-center gap-3 pt-2">
                <button
                  type="button"
                  onClick={() => setRenewingKey(null)}
                  className="flex-1 px-4 py-2.5 border border-[#374151] text-gray-300 rounded-lg text-sm font-medium hover:bg-[#374151] transition cursor-pointer"
                >
                  {translateText("Cancel", "انصراف", lang)}
                </button>
                <button
                  type="submit"
                  disabled={isRenewing}
                  className="flex-1 px-4 py-2.5 bg-emerald-600 hover:bg-emerald-500 text-white rounded-lg text-sm font-medium shadow-[0_0_15px_rgba(16,185,129,0.3)] transition cursor-pointer disabled:opacity-70 flex items-center justify-center gap-2"
                >
                  {isRenewing && <RefreshCw className="w-4 h-4 animate-spin" />}
                  {translateText("Submit Renewal", "ثبت تمدید", lang)}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
