import { translateText, Language } from "../lang/locales";
import React, { useState } from 'react';
import {
  Search,
  Key,
  Copy,
  Check,
  Ban,
  Trash2,
  RefreshCw,
  RotateCcw,
  QrCode,
  X,
  CreditCard
} from 'lucide-react';


// Assuming types from other files...
export function VpnKeysManager({
  keys,
  users,
  lang,
  toggleSubscriptionKey,
  setDeleteConfirm,  updateSubscriptionKey,
  servers = []
}: any) {
  const [searchTerm, setSearchTerm] = useState("");
  const [copiedKeyId, setCopiedKeyId] = useState<string | null>(null);
  const [activeQrKey, setActiveQrKey] = useState<any | null>(null);
  const [regeneratingKeyId, setRegeneratingKeyId] = useState<string | null>(null);
  const [renewingKey, setRenewingKey] = useState<any | null>(null);
  const [renewGb, setRenewGb] = useState("30");
  const [renewDays, setRenewDays] = useState("30");
  const [isRenewing, setIsRenewing] = useState(false);

  const t = {
    activeVpnKeysTitle: translateText('Active VPN Subscription Keys', 'کانفیگ‌ها و اشتراک‌های فعال VPN', lang),
    activeVpnKeysDesc: translateText('These represent the subscription links generated by the Python bot and saved in sqlite/3x-ui.', 'این کانفیگ‌ها مستقیماً لینک‌های تولید شده توسط ربات هستند که در دیتابیس ۳x-ui یا sqlite ذخیره شده‌اند.', lang),
    keySubLinkLabel: translateText('Subscription Link', 'لینک اتصال اختصاصی', lang),
    keyOwnerLabel: translateText('Owner ID/Handle', 'صاحب کانفیگ (کاربر)', lang),
    keyExpiryLabel: translateText('Expiry Date', 'تاریخ انقضا اکانت', lang)
  };

  const copyTextToClipboard = async (text: string) => {
    try {
      await navigator.clipboard.writeText(text);
    } catch (err) {
      console.error("Failed to copy:", err);
    }
  };

  const handleRegenerateUuid = async (keyId: string) => {
    if (!window.confirm(translateText("Are you sure you want to regenerate UUID and link? This will drop current connections.", "آیا از تغییر لینک و UUID این کانفیگ مطمئن هستید؟ این کار باعث قطع اتصال فعلی کاربر می‌شود.", lang))) return;
    
    setRegeneratingKeyId(keyId);
    try {
      const response = await fetch(`/api/subscription-keys/${keyId}/regenerate`, {
        method: "POST"
      });
      if (response.ok) {
        const result = await response.json();
        updateSubscriptionKey(keyId, {
          clientUuid: result.newUuid,
          subLink: result.newSubLink
        });
        alert(translateText("Link regenerated successfully!", "لینک با موفقیت تغییر کرد!", lang));
      } else {
        const err = await response.json();
        alert("Error: " + err.error);
      }
    } catch (err) {
      console.error(err);
      alert("Network error.");
    } finally {
      setRegeneratingKeyId(null);
    }
  };

  const handleRenewSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!renewingKey) return;
    setIsRenewing(true);
    try {
      const response = await fetch(`/api/subscription-keys/${renewingKey.id}/renew`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          addTrafficGb: parseFloat(renewGb) || 0,
          addDays: parseInt(renewDays) || 0
        })
      });

      if (response.ok) {
        const result = await response.json();
        updateSubscriptionKey(renewingKey.id, {
          trafficLimitGb: result.newTrafficLimitGb,
          expireDate: result.newExpireDate,
          status: 'active'
        });
        alert(translateText("Subscription renewed successfully!", "اشتراک با موفقیت تمدید شد!", lang));
        setRenewingKey(null);
      } else {
        const err = await response.json();
        alert("Error: " + err.error);
      }
    } catch (err) {
      console.error(err);
      alert("Network error");
    } finally {
      setIsRenewing(false);
    }
  };

  return (
    <div className="space-y-6 max-w-4xl mx-auto">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-6">
        <div>
          <h2 className="text-xl md:text-2xl font-display font-bold text-white flex items-center gap-3">
            <Key className="w-6 h-6 text-indigo-400" />
            {t.activeVpnKeysTitle}
          </h2>
          <p className="text-gray-400 text-sm mt-1">
            {t.activeVpnKeysDesc}
          </p>
        </div>
        <div className="relative w-full md:w-64">
          <input
            type="text"
            placeholder={translateText("Search config or user...", "جستجو کانفیگ یا کاربر...", lang)}
            className="w-full bg-[#111827] border border-[#374151] rounded-lg pl-10 pr-4 py-2 text-sm text-white focus:outline-none focus:border-indigo-500 transition"
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
          />
          <Search className="w-4 h-4 text-gray-400 absolute left-3 top-2.5" />
        </div>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-2 gap-4">
        {keys && Array.isArray(keys) ? keys.filter((key: any) => {
          if (!searchTerm) return true;
          const term = searchTerm.toLowerCase();
          const user = users?.find((u: any) => u.userId === key.userId);
          return (
            key.id.toLowerCase().includes(term) ||
            (key.clientName || "").toLowerCase().includes(term) ||
            (key.planName || "").toLowerCase().includes(term) ||
            String(key.userId).includes(term) ||
            (user?.username || "").toLowerCase().includes(term)
          );
        }).map((key: any) => {
          const user = users?.find((u: any) => u.userId === key.userId);
          return (
            <div key={key.id} className="bg-[#111827]/40 border border-slate-800/40 rounded-lg p-5 space-y-4 relative overflow-hidden group flex flex-col hover:border-cyan-500/50 transition-colors backdrop-blur-md">
              <div className="absolute top-0 right-0 h-1.5 w-full bg-cyan-500 shadow-[0_0_10px_rgba(34,211,238,0.5)]"></div>
              
              <div className="flex flex-col sm:flex-row justify-between items-start gap-4">
                <div>
                  <h4 className="font-semibold text-white text-base flex items-center gap-2">
                    {key.planName}
                  </h4>
                  <span className="text-xs text-gray-400 font-mono block mt-1">Key ID: {key.id}</span>
                  <span className="text-xs text-indigo-400 font-mono block mt-0.5" title="Client/Config Name">
                    Client Name: {key.clientName || 'N/A'}
                  </span>
                  <span className="text-xs text-gray-500 font-mono block mt-0.5" title="Telegram User ID">
                    Telegram ID: {key.userId}
                  </span>
                  <span className="text-xs text-gray-500 font-mono block mt-0.5 truncate" title="UUID">
                    UUID: {key.clientUuid || 'N/A'}
                  </span>
                </div>
                <div className="flex flex-wrap items-center gap-2">
                  <span className="px-2.5 py-1 rounded text-xs font-semibold bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 uppercase">
                    {key.status === "active" ? (translateText("active", "فعال", lang)) : (translateText("expired", "منقضی", lang))}
                  </span>
                  <button
                    onClick={() => {
                      copyTextToClipboard(key.subLink);
                      setCopiedKeyId(key.id);
                      setTimeout(() => setCopiedKeyId(null), 1500);
                    }}
                    className="px-2.5 py-1 bg-indigo-500/10 hover:bg-indigo-500/20 text-indigo-400 border border-indigo-500/20 hover:border-indigo-500/40 rounded text-xs font-medium flex items-center gap-1.5 transition-all cursor-pointer"
                    title={translateText("Copy subscription link", "کپی لینک کانفیگ", lang)}
                  >
                    {copiedKeyId === key.id ? (
                      <>
                        <Check className="w-3.5 h-3.5 text-emerald-400 animate-bounce" />
                        <span>{translateText("Copied", "کپی شد", lang)}</span>
                      </>
                    ) : (
                      <>
                        <Copy className="w-3.5 h-3.5 text-indigo-400" />
                        <span>{translateText("Copy", "کپی", lang)}</span>
                      </>
                    )}
                  </button>
                  <button
                    onClick={() => setActiveQrKey(key)}
                    className="px-2.5 py-1 bg-violet-500/10 hover:bg-violet-500/20 text-violet-400 border border-violet-500/20 hover:border-violet-500/40 rounded text-xs font-medium flex items-center gap-1.5 transition-all cursor-pointer"
                    title={translateText("Show QR Code", "نمایش بارکد QR", lang)}
                  >
                    <QrCode className="w-3.5 h-3.5 text-violet-400" />
                    <span>{translateText("QR", "بارکد", lang)}</span>
                  </button>
                  <button
                    type="button"
                    onClick={() => handleRegenerateUuid(key.id)}
                    disabled={regeneratingKeyId === key.id}
                    className="px-2.5 py-1 bg-rose-500/10 hover:bg-rose-500/20 text-rose-400 border border-rose-500/20 hover:border-rose-500/40 rounded text-xs font-medium flex items-center gap-1.5 transition-all cursor-pointer disabled:opacity-50"
                    title={translateText("Reset SubLink and UUID", "تغییر لینک و آیدی (UUID/subId)", lang)}
                  >
                    <RotateCcw className={`w-4 h-4 text-rose-400 ${regeneratingKeyId === key.id ? 'animate-spin' : ''}`} />
                    <span>{translateText("New Link", "تغییر لینک", lang)}</span>
                  </button>
                  <button
                    onClick={() => {
                      setRenewingKey(key);
                      setRenewGb("30");
                      setRenewDays("30");
                    }}
                    className="px-2.5 py-1 bg-emerald-500/10 hover:bg-emerald-500/20 text-emerald-400 border border-emerald-500/20 hover:border-emerald-500/40 rounded text-xs font-medium flex items-center gap-1.5 transition-all cursor-pointer"
                    title={translateText("Renew Subscription", "تمدید اشتراک", lang)}
                  >
                    <RefreshCw className="w-3.5 h-3.5 text-emerald-400" />
                    <span>{translateText("Renew", "تمدید", lang)}</span>
                  </button>
                  <button
                    onClick={() => toggleSubscriptionKey(key.id)}
                    className={`px-2.5 py-1 rounded text-xs font-medium flex items-center gap-1.5 transition-all cursor-pointer ${
                      key.status === "active"
                        ? "bg-amber-500/10 text-amber-500 border border-amber-500/20 hover:bg-amber-500/20"
                        : "bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 hover:bg-emerald-500/20"
                    }`}
                    title={key.status === "active" ? (translateText("Disable", "غیرفعال کردن", lang)) : (translateText("Enable", "فعال کردن", lang))}
                  >
                    <Ban className="w-3.5 h-3.5" />
                    <span>{key.status === "active" ? (translateText("Suspend", "تعلیق", lang)) : (translateText("Active", "فعال", lang))}</span>
                  </button>
                  <button
                    onClick={() => setDeleteConfirm({
                      id: key.id,
                      type: "key",
                      title: translateText("Confirm Delete Subscription", "تایید حذف کانفیگ", lang),
                      message: translateText(`Are you sure you want to delete config ${key.planName} (ID: ${key.id})?`, `آیا از حذف دائم کانفیگ ${key.planName} (شناسه: ${key.id}) اطمینان دارید؟`, lang)
                    })}
                    className="p-1.5 text-gray-400 hover:text-rose-400 hover:bg-rose-500/10 rounded transition cursor-pointer"
                    title={translateText("Delete VPN Subscription", "حذف کانفیگ", lang)}
                  >
                    <Trash2 className="w-4 h-4" />
                  </button>
                </div>
              </div>

              <div className="space-y-2 bg-[#1a2234] p-3.5 rounded-lg text-sm border border-slate-800">
                <div className="flex justify-between items-center">
                  <span className="text-gray-400 block text-xs uppercase font-mono tracking-wider font-semibold">{t.keySubLinkLabel}</span>
                  <button
                    onClick={() => {
                      copyTextToClipboard(key.subLink);
                      setCopiedKeyId(key.id);
                      setTimeout(() => setCopiedKeyId(null), 1500);
                    }}
                    className="text-indigo-400 hover:text-indigo-300 p-1 rounded transition cursor-pointer"
                    title={translateText("Copy Link", "کپی لینک", lang)}
                  >
                    {copiedKeyId === key.id ? (
                      <Check className="w-4 h-4 text-emerald-400 animate-pulse" />
                    ) : (
                      <Copy className="w-4 h-4" />
                    )}
                  </button>
                </div>
                <input
                  type="text"
                  readOnly
                  className="bg-black/30 border border-slate-800 rounded p-2 text-xs text-indigo-300 font-mono w-full focus:outline-none select-all"
                  value={key.subLink}
                />
              </div>

              <div className="grid grid-cols-2 gap-4 text-sm pt-4 text-gray-400 border-t border-slate-800">
                <div>
                  <span className="text-xs block text-gray-500 mb-1">{t.keyOwnerLabel}:</span>
                  <span className="text-white font-mono font-medium text-sm">@{user?.username || key.userId}</span>
                </div>
                <div>
                  <span className="text-xs block text-gray-500 mb-1">{t.keyExpiryLabel}:</span>
                  <span className="text-gray-200 font-mono text-sm">{key.expireDate}</span>
                </div>
                {key.serverId && (
                  <div className="col-span-2">
                    <span className="text-xs block text-gray-500 mb-1">{translateText("Server:", "سرور:", lang)}</span>
                    <span className="text-white font-mono text-sm block bg-black/20 p-2 rounded border border-slate-800">
                      {servers.find((s: any) => String(s.id) === String(key.serverId))?.name || key.serverId}
                    </span>
                  </div>
                )}
                <div className="col-span-2">
                  <span className="text-xs block text-gray-500 mb-1">{translateText("Used / Remaining data:", "حجم مصرفی / باقی‌مانده:", lang)}</span>
                  <span className="text-white font-mono text-sm block bg-black/20 p-2 rounded border border-slate-800">
                    <span className="text-rose-400">{Number(key.trafficUsedGb || 0).toFixed(2)} GB</span>
                    <span className="text-gray-600 mx-2">/</span>
                    <span className="text-emerald-400 font-bold">{Math.max(0, Number(key.trafficLimitGb || 0) - Number(key.trafficUsedGb || 0)).toFixed(2)} GB</span>
                    <span className="text-gray-500 ml-3">({translateText("Total:", "کل:", lang)} {Number(key.trafficLimitGb || 0).toFixed(2)} GB)</span>
                  </span>
                </div>
              </div>
            </div>
          );
        }) : (
          <div className="col-span-full py-12 text-center text-gray-500 bg-slate-900/20 rounded-2xl border border-white/5">
            {translateText("No VPN configs found", "هیچ کانفیگی یافت نشد", lang)}
          </div>
        )}
      </div>

      {/* QR Code Dialog Modal */}
      {activeQrKey && (
        <div className="fixed inset-0 bg-black/80 backdrop-blur-sm flex items-center justify-center p-4 z-50">
          <div className="bg-white p-6 rounded-2xl max-w-sm w-full space-y-6 relative flex flex-col items-center">
            <button
              onClick={() => setActiveQrKey(null)}
              className="absolute top-4 right-4 text-gray-400 hover:text-gray-600 bg-gray-100 hover:bg-gray-200 p-1.5 rounded-full transition-colors cursor-pointer"
            >
              <X className="w-5 h-5" />
            </button>
            <div className="text-center space-y-1">
              <h3 className="font-display font-bold text-gray-900 text-xl">{activeQrKey.planName}</h3>
              <p className="text-gray-500 text-sm font-mono">{activeQrKey.clientName}</p>
            </div>
            
            <div className="p-4 bg-gray-50 rounded-xl border border-gray-100">
              <img
                src={`https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=${encodeURIComponent(activeQrKey.subLink)}`}
                alt="VPN Connection QR Code"
                className="w-full h-auto aspect-square rounded select-none"
                referrerPolicy="no-referrer"
              />
            </div>
            
            <p className="text-center text-gray-500 text-xs">
              {translateText("Scan this QR code with your client app to connect.", "برای اتصال، این بارکد را با اپلیکیشن کلاینت خود اسکن کنید.", lang)}
            </p>
          </div>
        </div>
      )}

      {/* Renew Subscription Modal */}
      {renewingKey && (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-xs flex items-center justify-center p-4 z-50">
          <div className="bg-[#111827] border border-[#1f2937] p-6 rounded-xl max-w-md w-full space-y-5">
            <h3 className="font-display font-semibold text-lg text-white flex items-center gap-2">
              <RefreshCw className="w-5 h-5 text-emerald-400" />
              {translateText("Renew & Recharge Subscription", "تمدید و شارژ اشتراک", lang)}
            </h3>
            
            <div className="bg-[#1a2234] p-3 rounded-lg border border-[#374151] space-y-1">
              <p className="text-sm text-gray-300">
                <span className="text-gray-500 mr-2">{translateText("User:", "کاربر:", lang)}</span>
                <span className="font-mono text-indigo-400">{renewingKey.clientName}</span>
              </p>
              <p className="text-sm text-gray-300">
                <span className="text-gray-500 mr-2">{translateText("Plan:", "پلن:", lang)}</span>
                <span>{renewingKey.planName}</span>
              </p>
            </div>

            <form onSubmit={handleRenewSubmit} className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-1">
                  {translateText("Add Traffic (GB)", "اضافه کردن حجم (گیگابایت)", lang)}
                </label>
                <input
                  type="number"
                  min="0"
                  step="0.1"
                  required
                  className="w-full bg-[#1a2234] border border-[#374151] rounded-lg px-4 py-2.5 text-white focus:outline-none focus:border-emerald-500 focus:ring-1 focus:ring-emerald-500 transition-all font-mono"
                  value={renewGb}
                  onChange={(e) => setRenewGb(e.target.value)}
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-300 mb-1">
                  {translateText("Add Time (Days)", "اضافه کردن زمان (روز)", lang)}
                </label>
                <input
                  type="number"
                  min="0"
                  required
                  className="w-full bg-[#1a2234] border border-[#374151] rounded-lg px-4 py-2.5 text-white focus:outline-none focus:border-emerald-500 focus:ring-1 focus:ring-emerald-500 transition-all font-mono"
                  value={renewDays}
                  onChange={(e) => setRenewDays(e.target.value)}
                />
              </div>

              <div className="flex items-center gap-3 pt-2">
                <button
                  type="button"
                  onClick={() => setRenewingKey(null)}
                  className="flex-1 px-4 py-2.5 border border-[#374151] text-gray-300 rounded-lg text-sm font-medium hover:bg-[#374151] transition cursor-pointer"
                >
                  {translateText("Cancel", "انصراف", lang)}
                </button>
                <button
                  type="submit"
                  disabled={isRenewing}
                  className="flex-1 px-4 py-2.5 bg-emerald-600 hover:bg-emerald-500 text-white rounded-lg text-sm font-medium shadow-[0_0_15px_rgba(16,185,129,0.3)] transition cursor-pointer disabled:opacity-70 flex items-center justify-center gap-2"
                >
                  {isRenewing && <RefreshCw className="w-4 h-4 animate-spin" />}
                  {translateText("Submit Renewal", "ثبت تمدید", lang)}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
